print("欢迎来到名片系统".center(30,"*"))
input(print("1:增加名片".center(30," ")))
input(print("2:修过名片".center(30," ")))
input(print("3:查找名片".center(30," ")))
input(print("4:删除名片".center(30," ")))
input(print("5:退出名片".center(30," ")))
